# action.yml
name: 'Hugo Asciidoctor Html Action'
description: 'Action to generate static website using hugo by supporting AsciiDoc html output'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'  
  color: 'blue'
